spring.mongodb.uri=mongodb://localhost:27017
spring.mongodb.database=socialpulse

server.port=8080

jwt.secret=SocialPulseSuperSecretKeyForJWTAuthentication2026Secure
jwt.expiration=86400000


# ==========================================
# FILE UPLOAD SETTINGS
# ==========================================

spring.servlet.multipart.enabled=true

# Maximum size of one uploaded file
spring.servlet.multipart.max-file-size=100MB

# Maximum size of complete request
spring.servlet.multipart.max-request-size=110MB